# Generated by Django 5.0.7 on 2024-07-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Influencer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("niche", models.CharField(max_length=100)),
                ("reach", models.IntegerField()),
            ],
        ),
    ]
