# Generated by Django 5.0.7 on 2024-07-27 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("influencer", "0001_initial"),
        ("main", "0002_alter_myuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="influencer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="influencer.influencer",
            ),
        ),
    ]
