# Generated by Django 5.0.7 on 2024-07-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_sponsor_campaign_campaign_sponsor"),
    ]

    operations = [
        migrations.AddField(
            model_name="negotiate",
            name="amt",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
