# Generated by Django 5.0.7 on 2024-07-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_negotiate_amt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adrequest",
            name="sponsor",
        ),
        migrations.AddField(
            model_name="adrequest",
            name="name",
            field=models.CharField(default="sample", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adrequest",
            name="requirements",
            field=models.CharField(default="najksndaksj", max_length=2000),
            preserve_default=False,
        ),
    ]
